USE [SG_Blazor_App]
GO
SET IDENTITY_INSERT [dbo].[Atenciones] ON 
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27329, N'SAN GABRIEL', N'EXAMENES ADICIONALES', CAST(N'2021-11-11' AS Date), N'RIOS GUEVARA MARIO ARTURO', N'43657193', N'INSTITUTO DE SEGURIDAD Y SALUD OCUPACIONAL S.A.C. - ISSO MEDIC S.A.C.', N'TIENDAS DEL MEJORAMIENTO DEL HOGAR S.A.', N'', N'', N'OPERACIONES', N'JEFE DE DEPARTAMENTO/OPERADOR LOG�STICO DE EQUIPO MOTORIZADO', N'Calderon Rodriguez Michelle', CAST(N'08:04:25' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27330, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'SARMIENTO MU�OZ JUAN CARLOS', N'45729356', N'MAQUINARIAS E INGENIERIA METALMECANICA S.A. - MAQUINSA', N'', N'', N'CONTROL AUDIOMETRIA', N'OPERATIVO', N'SUPERVISOR DE SEGURIDAD', N'Diaz Vizcarra Guillermo Franco', CAST(N'08:05:15' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27331, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'CORNEJO GUILLEN JOSE MIGUEL', N'43209659', N'PARTICULAR', N'CORPORACION SOLUCIONES DE GESTION S.A.C', N'', N'COVID', N'', N'', N'Oviedo Morante Claudia', CAST(N'08:06:30' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27332, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'ARENAS CHAVEZ FREDY HERNAN', N'40521456', N'COMPA�IA MINERA ANTAPACCAY S.A. (CONTRATISTAS)', N'TM MAQUINARIA S A', N'', N'COVID', N'', N'', N'Ramonez Dominguez Jose Alejandro', CAST(N'08:07:28' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27333, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'CORNEJO GUILLEN GIANCARLO', N'45282679', N'PARTICULAR', N'CORPORACION SOLUCIONES DE GESTION S.A.C', N'', N'COVID', N'', N'', N'Oviedo Morante Claudia', CAST(N'08:07:33' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27334, N'SAN GABRIEL', N'PRE OCUPACIONAL', CAST(N'2021-11-11' AS Date), N'CUBA YNCA KATHERINE DORALI', N'76376438', N'IHEALTH S.A.C. - CHECK SALUD', N'CURTIEMBRE BUENAVENTURA S.A.C.', N'', N'SUR LEDER (Protocolo 1)', N'OPERATIVO', N'ASISTENTE DE PRODUCCI�N', N'Calderon Rodriguez Michelle', CAST(N'08:09:00' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27335, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'PHILCO ALEGRE VICTOR NOE', N'43166047', N'HUDBAY PERU S.A.C.', N'TRANSPORTES IBEROAMERICANO S.R.L.', N'', N'COVID', N'OTROS', N'CONDUCTOR', N'Ramonez Dominguez Jose Alejandro', CAST(N'08:09:41' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27336, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'VELASQUEZ QUISPE EUSTAQUIO', N'40318762', N'COMPA�IA MINERA ANTAPACCAY S.A.', N'NICOLCH & VARGAS PERU S.A.C.', N'', N'LA-0069-21', N'', N'', N'Chise Ayta Jonathan Alexander', CAST(N'08:12:03' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27337, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'CASTELLANOS QUISPE ANGEL', N'25188476', N'COMPA�IA MINERA ANTAPACCAY S.A.', N'TRANSPORTES ELIO S.A.C.', N'', N'LA-0069-21', N'', N'', N'Chise Ayta Jonathan Alexander', CAST(N'08:12:47' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27338, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'MORENO MAMANI JOSE GABRIEL', N'1342416', N'COMPA�IA MINERA ANTAPACCAY S.A.', N'EXSA S A', N'', N'LA-0069-21', N'', N'', N'Chise Ayta Jonathan Alexander', CAST(N'08:15:18' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27339, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'ENRIQUEZ MAMANI JOSE PABLO', N'29226199', N'J & V RESGUARDO S.A.C. - LIDERMAN', N'', N'', N'COVID', N'', N'', N'Diaz Vizcarra Guillermo Franco', CAST(N'08:15:25' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27340, N'SAN GABRIEL', N'PRE OCUPACIONAL', CAST(N'2021-11-11' AS Date), N'YAHUIRA CONDORI REYNALDO', N'43613644', N'MINERA LAS BAMBAS S.A.', N'INVERSIONES MARITIMAS DEL PACIFICO SUR S.A.C.', N'', N'CONTRATISTAS 2021-2023', N'PERFORACION Y VOLADURA/OPERACIONES MINA', N'CONDUCTOR SEMITRAILER', N'Diaz Vizcarra Guillermo Franco', CAST(N'07:52:31' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27341, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'CONDORI CALLA FREDY LUIS', N'43019628', N'COMPA�IA MINERA ANTAPACCAY S.A.', N'TRANSPORTES HAGEMSA S.A.C.', N'', N'LA-0069-21', N'', N'', N'Chise Ayta Jonathan Alexander', CAST(N'07:51:08' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27342, N'SAN GABRIEL', N'PRE OCUPACIONAL', CAST(N'2021-11-11' AS Date), N'CHAVARRIA ROCHA ELARD ANTONY', N'75418137', N'OL LOS ANDES S.A.C.', N'', N'', N'BACKUS-OPERARIO', N'DIVISION BACKUS', N'OPERARIO', N'Oviedo Morante Claudia', CAST(N'07:41:39' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27343, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'SAICO SAICO CEFERINO', N'40042243', N'COMPA�IA MINERA ANTAPACCAY S.A.', N'SERVOSA CARGO S.A.C.', N'', N'LA-0069-21', N'', N'', N'Chise Ayta Jonathan Alexander', CAST(N'07:42:08' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27344, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'ZU�IGA DELGADO JESUS ANTONIO', N'30835752', N'COMPA�IA MINERA ANTAPACCAY S.A.', N'SERVOSA CARGO S.A.C.', N'', N'LA-0069-21', N'', N'', N'Chise Ayta Jonathan Alexander', CAST(N'07:42:37' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27345, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'CORREA SUAREZ JOSE IGNACIO', N'42603618', N'COMPA�IA MINERA ANTAPACCAY S.A.', N'SERVOSA CARGO S.A.C.', N'', N'LA-0069-21', N'', N'', N'Chise Ayta Jonathan Alexander', CAST(N'07:43:07' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27346, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'TORRES TAFUR ANTONIO', N'10066377', N'COMPA�IA MINERA ANTAPACCAY S.A.', N'TERPEL COMERCIAL DEL PERU S.R.L.', N'', N'LA-0069-21', N'', N'', N'Chise Ayta Jonathan Alexander', CAST(N'07:43:40' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27347, N'SAN GABRIEL', N'PRE OCUPACIONAL', CAST(N'2021-11-11' AS Date), N'MAMANI CHOQUE HENRY ALFREDO', N'30583323', N'INTERNATIONAL PRIVATE SECURITY PERU S.A.C. - FORTUNIC', N'', N'', N'AGENTE DE SEGURIDAD', N'SEGURIDAD PATRIMONIAL', N'PREVENCIONISTA', N'Diaz Vizcarra Guillermo Franco', CAST(N'07:44:16' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27348, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'MOROCO CABRERA NILTON CHRISTEAN', N'40705844', N'MAQUINARIAS E INGENIERIA METALMECANICA S.A. - MAQUINSA', N'', N'', N'CONTROL AUDIOMETRIA', N'', N'', N'Ramonez Dominguez Jose Alejandro', CAST(N'07:46:05' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27349, N'SAN GABRIEL', N'PRE OCUPACIONAL', CAST(N'2021-11-11' AS Date), N'CORNEJO GUILLEN JOSE MIGUEL', N'43209659', N'SALUD OCUPACIONAL INTEGRAL SAN GABRIEL S.A.C.', N'CORPORACION SOLUCIONES DE GESTION S.A.C', N'', N'ANEXO 16', N'OPERATIVO', N'GERENTE COMERCIAL', N'Oviedo Morante Claudia', CAST(N'07:48:08' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27350, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'HUANCA HUANCA DOMINGO', N'45098825', N'COMPA�IA MINERA ANTAPACCAY S.A.', N'TRANSPORTES HAGEMSA S.A.C.', N'', N'LA-0069-21', N'', N'', N'Chise Ayta Jonathan Alexander', CAST(N'07:48:38' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27351, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'CALLO SOLIS ALBERTO', N'30857900', N'COMPA�IA MINERA ANTAPACCAY S.A.', N'EXSA S A', N'', N'LA-0069-21', N'', N'', N'Chise Ayta Jonathan Alexander', CAST(N'07:49:08' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27352, N'SAN GABRIEL', N'EXAMENES ADICIONALES', CAST(N'2021-11-11' AS Date), N'CHOQUECOTA CRUZ EDWIN CRISS', N'70550617', N'SERVICIOS MEDICOS EL TREBOL S.A.C.', N'J & V RESGUARDO S.A.C. - LIDERMAN', N'', N'LIDERMAN-UNICO', N'J&V RESGUARDO SAC', N'AGENTE DE SEGURIDAD', N'Calderon Rodriguez Michelle', CAST(N'07:49:27' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27353, N'SAN GABRIEL', N'EXAMENES ADICIONALES', CAST(N'2021-11-11' AS Date), N'CORNEJO GUILLEN JOSE MIGUEL', N'43209659', N'PARTICULAR', N'', N'', N'', N'', N'', N'Oviedo Morante Claudia', CAST(N'08:49:14' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27354, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'QUISPE LOPE BENANCIO', N'40842791', N'HUDBAY PERU S.A.C.', N'TRANSPORTES IBEROAMERICANO S.R.L.', N'', N'COVID', N'OTROS', N'CONDUCTOR', N'Ramonez Dominguez Jose Alejandro', CAST(N'07:49:29' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27355, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'LEON IQUIAPAZA LUIS', N'29665234', N'COMPA�IA MINERA ANTAPACCAY S.A.', N'TRANSPORTES ELIO S.A.C.', N'', N'LA-0069-21', N'', N'', N'Chise Ayta Jonathan Alexander', CAST(N'07:49:40' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27356, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'LLERENA ZU�IGA WALTER OSWALDO', N'29710520', N'COMPA�IA MINERA ANTAPACCAY S.A.', N'EXSA S A', N'', N'LA-0069-21', N'', N'', N'Chise Ayta Jonathan Alexander', CAST(N'07:50:11' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27357, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'CHIPANA ORDO�O DAVID JUSTO', N'484237', N'COMPA�IA MINERA ANTAPACCAY S.A.', N'EXSA S A', N'', N'LA-0069-21', N'', N'', N'Chise Ayta Jonathan Alexander', CAST(N'07:50:36' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27358, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'CHECYA AGUILAR WILFREDO', N'42588833', N'HUDBAY PERU S.A.C.', N'TRANSPORTES ACOINSA S.A.C.', N'', N'COVID', N'OTROS', N'CONDUCTOR', N'Ramonez Dominguez Jose Alejandro', CAST(N'07:50:42' AS Time), NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Atenciones] ([IdAtenciones], [Local0], [TipExa], [FecAte], [NomApe], [DocIde], [Empres], [SubCon], [Proyec], [Perfil], [Area], [PueTra], [PeReAd], [Hora], [AleMed], [AleAud], [AleEnf], [AlEnHc]) VALUES (27359, N'SAN GABRIEL', N'OTROS', CAST(N'2021-11-11' AS Date), N'RIOS MINAYA REYNALDO', N'31044163', N'HUDBAY PERU S.A.C.', N'SERVOSA CARGO S.A.C.', N'', N'COVID', N'OTROS', N'CONDUCTOR', N'Oviedo Morante Claudia', CAST(N'08:17:33' AS Time), NULL, NULL, NULL, NULL)
GO
SET IDENTITY_INSERT [dbo].[Atenciones] OFF
GO
